'use strict';

export default [
  "Rwanda",
  "Somalia",
  "Yemen",
  "Iraq",
  "Saudi Arabia",
  "Iran",
  "Cyprus",
  "Tanzania",
  "Syria",
  "Armenia",
  "Kenya",
  "Congo",
  "Djibouti",
  "Uganda",
  "Central African Republic",
  "Seychelles",
  "Hashemite Kingdom of Jordan",
  "Lebanon",
  "Kuwait",
  "Oman",
  "Qatar",
  "Bahrain",
  "United Arab Emirates",
  "Israel",
  "Turkey",
  "Ethiopia",
  "Eritrea",
  "Egypt",
  "Sudan",
  "Greece",
  "Burundi",
  "Estonia",
  "Latvia",
  "Azerbaijan",
  "Republic of Lithuania",
  "Svalbard and Jan Mayen",
  "Georgia",
  "Republic of Moldova",
  "Belarus",
  "Finland",
  "Åland",
  "Ukraine",
  "Macedonia",
  "Hungary",
  "Bulgaria",
  "Albania",
  "Poland",
  "Romania",
  "Kosovo",
  "Zimbabwe",
  "Zambia",
  "Comoros",
  "Malawi",
  "Lesotho",
  "Botswana",
  "Mauritius",
  "Swaziland",
  "Réunion",
  "South Africa",
  "Mayotte",
  "Mozambique",
  "Madagascar",
  "Afghanistan",
  "Pakistan",
  "Bangladesh",
  "Turkmenistan",
  "Tajikistan",
  "Sri Lanka",
  "Bhutan",
  "India",
  "Maldives",
  "British Indian Ocean Territory",
  "Nepal",
  "Myanmar [Burma]",
  "Uzbekistan",
  "Kazakhstan",
  "Kyrgyzstan",
  "Palau",
  "Vietnam",
  "Thailand",
  "Indonesia",
  "Laos",
  "Taiwan",
  "Philippines",
  "Malaysia",
  "China",
  "Hong Kong",
  "Brunei",
  "Macao",
  "Cambodia",
  "Republic of Korea",
  "Japan",
  "North Korea",
  "Singapore",
  "Cook Islands",
  "East Timor",
  "Russia",
  "Mongolia",
  "Australia",
  "Marshall Islands",
  "Federated States of Micronesia",
  "Papua New Guinea",
  "Solomon Islands",
  "Tuvalu",
  "Nauru",
  "Vanuatu",
  "New Caledonia",
  "Norfolk Island",
  "New Zealand",
  "Fiji",
  "Libya",
  "Cameroon",
  "Senegal",
  "Republic of the Congo",
  "Portugal",
  "Liberia",
  "Ivory Coast",
  "Ghana",
  "Equatorial Guinea",
  "Nigeria",
  "Burkina Faso",
  "Togo",
  "Guinea-Bissau",
  "Mauritania",
  "Benin",
  "Gabon",
  "Sierra Leone",
  "São Tomé and Príncipe",
  "Gibraltar",
  "Gambia",
  "Guinea",
  "Chad",
  "Niger",
  "Mali",
  "Tunisia",
  "Spain",
  "Morocco",
  "Malta",
  "Algeria",
  "Faroe Islands",
  "Denmark",
  "Iceland",
  "United Kingdom",
  "Switzerland",
  "Sweden",
  "Netherlands",
  "Austria",
  "Belgium",
  "Germany",
  "Luxembourg",
  "Ireland",
  "Monaco",
  "France",
  "Andorra",
  "Liechtenstein",
  "Jersey",
  "Isle of Man",
  "Guernsey",
  "Slovak Republic",
  "Czech Republic",
  "Norway",
  "Vatican City",
  "San Marino",
  "Italy",
  "Slovenia",
  "Montenegro",
  "Croatia",
  "Bosnia and Herzegovina",
  "Angola",
  "Namibia",
  "Barbados",
  "Cape Verde",
  "Guyana",
  "French Guiana",
  "Suriname",
  "Saint Pierre and Miquelon",
  "Greenland",
  "Paraguay",
  "Uruguay",
  "Brazil",
  "Falkland Islands",
  "Jamaica",
  "Dominican Republic",
  "Cuba",
  "Martinique",
  "Bahamas",
  "Bermuda",
  "Anguilla",
  "Trinidad and Tobago",
  "Saint Kitts and Nevis",
  "Dominica",
  "Antigua and Barbuda",
  "Saint Lucia",
  "Turks and Caicos Islands",
  "Aruba",
  "British Virgin Islands",
  "Saint Vincent and the Grenadines",
  "Montserrat",
  "Saint Martin",
  "Saint-Barthélemy",
  "Guadeloupe",
  "Grenada",
  "Cayman Islands",
  "Belize",
  "El Salvador",
  "Guatemala",
  "Honduras",
  "Nicaragua",
  "Costa Rica",
  "Venezuela",
  "Ecuador",
  "Colombia",
  "Panama",
  "Haiti",
  "Argentina",
  "Chile",
  "Bolivia",
  "Peru",
  "Mexico",
  "French Polynesia",
  "Kiribati",
  "Tokelau",
  "Tonga",
  "Wallis and Futuna",
  "Samoa",
  "Niue",
  "Northern Mariana Islands",
  "Guam",
  "Puerto Rico",
  "U.S. Virgin Islands",
  "U.S. Minor Outlying Islands",
  "American Samoa",
  "Canada",
  "United States",
  "Palestine",
  "Serbia",
  "Antarctica",
  "Sint Maarten",
  "Curaçao",
  "Bonaire, Sint Eustatius, and Saba",
  "South Sudan"
]
