version: '2'
services:
  wp:
      image: wordpress:latest
      environment:
       - WORDPRESS_DB_PASSWORD=my-secret-pw
      cpu_shares: 100
      mem_limit: 524288000
      links:
       - mysql

      ports:
        - "80:80"
      volumes:
        - /home/ec2-user/rfr:/var/www/html/wp-content

  mysql:
      image: mysql:latest
      cpu_shares: 100
      mem_limit: 524288000
      environment:
       - MYSQL_ROOT_PASSWORD=my-secret-pw
      ports:
       - "3306:3306"
      volumes:
       - /home/ec2-user/mysqldata:/var/lib/mysql
