<?php
function getLanguages() {
  return [
    "Acholi",
    "Afar",
    "Afrikaans ",
    "Albanian",
    "Amharic",
    "Angolar",
    "Antiguan Creole",
    "Arab",
    "Arabic",
    "Aragonese",
    "Armenian",
    "Astur-Leonese",
    "Aymara ",
    "Aynu",
    "Azeri",
    "Bahasa Malaysia",
    "Bambara",
    "Baoulé",
    "Barbadian",
    "Basque",
    "Belarusian",
    "Belize Creole",
    "Bengali",
    "Berber",
    "Bété",
    "Bislama ",
    "Bosnian",
    "Bulgarian",
    "Burmese",
    "Cantonese",
    "Catalan",
    "Chichewa",
    "Chinese local religions",
    "Chinese",
    "Chuukese",
    "Creole",
    "Croatian",
    "Cypriot Arabic",
    "Dagomba",
    "Danish",
    "Dari",
    "Dinka",
    "Dioula",
    "Djerma ",
    "Dominican Creole French ",
    "Dutch",
    "Dzongkha",
    "English",
    "Estonian",
    "Ewe",
    "Faroese",
    "Fijian",
    "Filipino",
    "Finnish",
    "Fon and Yoruba",
    "Forro",
    "French",
    "Frisian",
    "Fulani",
    "Fulbe",
    "Galician",
    "Garifuna",
    "Georgian",
    "German",
    "Gilbertese",
    "Gorani",
    "Greek",
    "Greenlandic ",
    "Grenadian French Creole",
    "Guaraní",
    "Haitian Creole",
    "Hausa",
    "Hebrew",
    "Hindi",
    "Hiri Motu",
    "Hungarian",
    "Icelandic",
    "Igbo (Ibo)",
    "Indonesian",
    "Irish",
    "IsiNdebele",
    "IsiXhosa",
    "IsiZulu",
    "Itak",
    "Italian",
    "Jamaican creole  ",
    "Japanese",
    "Jola",
    "Kabye ",
    "Kamba",
    "Kazakh",
    "Khmer",
    "Kichwa",
    "Kikuyu",
    "Kinyarwanda",
    "Kirundi ",
    "Kituba",
    "Kituba",
    "Korean ",
    "Kosraean ",
    "Krio",
    "Kru",
    "Kurdish ",
    "Kyrgyz",
    "Lao",
    "Latviana",
    "Lingala",
    "Lingala ",
    "Lithuanian",
    "Luganda",
    "Luo",
    "Luxembourgish",
    "Macedonian ",
    "Malagasy French ",
    "Malay",
    "Maldivian (Dhivehi)",
    "Malinke",
    "Maltese",
    "Mandarin",
    "Mande",
    "Mandinka",
    "Maori",
    "Marshallese",
    "Mauritian Creole",
    "Mayan",
    "Mel",
    "Mende",
    "Mina",
    "Mirandese",
    "Mocoví",
    "Moldovan",
    "Monegasque",
    "Mongolian ",
    "Montenegrin",
    "Nauruan",
    "Ndebele",
    "Nepali",
    "Nordic languages",
    "Norwegian (Bokmål / Nynorsk)",
    "Nuer",
    "Occitan ",
    "Palauan ",
    "Papua New Guinean Sign Language, ",
    "Pashto",
    "Persian",
    "Pohnpeian",
    "Polish",
    "Portuguese",
    "Principense",
    "Pulaar",
    "Qom",
    "Quechua",
    "Romani",
    "Romanian",
    "Romansh",
    "Russian",
    "Ryukyuan languages",
    "Sami",
    "Samoan",
    "Sangho",
    "Sara",
    "Senoufo",
    "Sepedi",
    "Serbian ",
    "Sesotho",
    "Sesotho",
    "Setswana",
    "Setswana",
    "Setu ",
    "Seychellois Creole",
    "Shilluk",
    "Shona ",
    "Shuar  ",
    "Sinhalese",
    "SiSwati",
    "Slovak",
    "Somali",
    "Soninke",
    "Sonsorolese",
    "Spanish",
    "Susu",
    "Swahili",
    "Swedish ",
    "Swedish (official)",
    "Tajik",
    "Tajik Uzbek",
    "Tamil",
    "Temne",
    "Tetum",
    "Thai",
    "Tibetan",
    "Tigrinya",
    "Tobian ",
    "Tok Pisin",
    "Tongan",
    "Tribal languages",
    "Tshiluba",
    "Tshivenda",
    "Turkish",
    "Turkmen",
    "Tuvaluan",
    "Ukrainian",
    "Urdu",
    "Uyghur",
    "Uzbek",
    "Vietnamese",
    "Võro",
    "Wichi",
    "Wolof",
    "Xhosa",
    "Xinca",
    "Xitsonga",
    "Yapese",
    "Yoruba ",
    "Zhuang",
    "Zulu",
    "Slovene"
  ];
}

 ?>
