version: '2'
services:
  wp:
      build: .
      links:
       - mysql
      environment:
        - WORDPRESS_DB_PASSWORD=my-secret-pw
      ports:
        - "80:80"
      volumes:
        - ..:/var/www/html/wp-content
  mysql:
      image: mysql:latest
      environment:
       - MYSQL_ROOT_PASSWORD=my-secret-pw
      ports:
       - "3307:3306"
      volumes:
       - ~/mysqldata_rfr:/var/lib/mysql
  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   links:
  #     - mysql
  #   environment:
  #     - PMA_HOST=mysql
  #   ports:
  #     - "9090:80"
